targets/boards/kameleon-core/src/pwm.c
targets/shared/drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c

PWM setFrequency function bug fix

---

include/port/i2c.h
src/modules/i2c/i2c_magic_strings.h
src/modules/i2c/module_i2c.c
targets/boards/kameleon-core/src/i2c.c

I2C init parameter change
- bus, mode(master/slave), speed
I2C max speed is 400KHz (fast mode)

disable I2C slave mode - temporary.

---

src/runtime.c

Delete JERRY_INIT_MEM_STATS option

---

include/port/i2c.h
src/modules/i2c/i2c_magic_strings.h
src/modules/i2c/module_i2c.c
targets/boards/kameleon-core/src/i2c.c

- Resolve issue #90
MASTER mode is default in i2c init function

I2C memory read/write function implementation

---

include/io.h
include/repl.h
src/io.c
src/main.c
src/repl.c

run clear the javascript context before .load command
- resolve issue #92, issue #93

clear all the event list in .clear command

---

src/runtime.c
targets/boards/kameleon-core/src/system.c

GPIO init at bootup and .reset command

---

src/modules/pwm/module_pwm.c
targets/boards/kameleon-core/src/pwm.c

Deinit GPIO at PWM.close()

---

targets/boards/kameleon-core/src/spi.c

SPI clock bug fix

---

targets/boards/kameleon-core/src/spi.c

SPI.recv() function buf fix

---

include/port/spi.h
src/modules/spi/module_spi.c
src/modules/spi/spi_magic_strings.h
targets/boards/kameleon-core/src/spi.c

Remove bits option in SPI class

---

src/global.c
src/modules/pwm/module_pwm.c
src/runtime.c

Fix the error message display issue in the console window

---

include/port/system.h
src/runtime.c
targets/boards/kameleon-core/src/adc.c
targets/boards/kameleon-core/src/gpio.c
targets/boards/kameleon-core/src/i2c.c
targets/boards/kameleon-core/src/pwm.c
targets/boards/kameleon-core/src/spi.c
targets/boards/kameleon-core/src/system.c
targets/boards/kameleon-core/src/uart.c

Implement *_cleanup() function for all peripherals.

---

include/port/system.h
src/main.c
targets/boards/kameleon-core/src/system.c

- skipping to run user scirpt if the button is pressed at 1 sec after power on.
- Resolve the issue #142

Adding script loading check after 1sec

---

include/port/main.h
include/port/system.h
targets/boards/kameleon-core/src/adc.c
targets/boards/kameleon-core/src/flash.c
targets/boards/kameleon-core/src/pwm.c
targets/boards/kameleon-core/src/usbd_conf.c

Move _Error_Handler function to system.h

---

include/port/system.h
targets/boards/kameleon-core/include/kameleon_core.h
targets/boards/kameleon-core/include/stm32f4xx_it.h
targets/boards/kameleon-core/src/adc.c
targets/boards/kameleon-core/src/flash.c
targets/boards/kameleon-core/src/pwm.c
targets/boards/kameleon-core/src/stm32f4xx_it.c
targets/boards/kameleon-core/src/system.c
targets/boards/kameleon-core/src/tty.c
targets/boards/kameleon-core/src/usbd_conf.c

Move Kameleon-core specific code in /port/system.h to the targets

---

include/magic_strings.h
include/port/gpio.h
include/port/system.h
src/global.c
targets/boards/kameleon-core/src/gpio.c
targets/boards/kameleon-core/src/system.c

implement pulseRead, pulseWrite functions.

---

include/port/storage.h
targets/boards/kameleon-core/Make.def
targets/boards/kameleon-core/src/storage.c

- Changes for the issue #180
Storage.h file is changed. please check the changes in the commit
storage_space() function is added in the storage.h please let me know if this function is not needed.

Storage functions

---

include/port/storage.h
src/modules/storage/module_storage.c
targets/boards/kameleon-core/src/storage.c

Changes for the issue #180 
- Remove size in the function and treat buffer as a string format.
- new error code.

storage interface change

---

targets/boards/kameleon-core/src/i2c.c

i2c close function bug fix

---

esp32/main/targets/boards/esp32-devkitc/src/gpio.c

GPIO INPUT_PULLUP bug fix

---

src/modules/button/button.js

Button event parameter does not hava a default value

---

esp32/main/targets/boards/esp32-devkitc/src/spi.c

fix cpu halt when SPI is initialized twice

---

esp32/main/CMakeLists.txt
esp32/main/targets/boards/esp32-devkitc/src/system.c
esp32/main/targets/boards/esp32-devkitc/src/tcp.c
esp32/main/targets/boards/esp32-devkitc/target.cmake
include/io.h
include/port/tcp.h
src/io.c
src/modules/net/module.json
src/modules/net/module_net.c
src/modules/net/module_net.h
src/modules/net/net.js

Added HAL device driver for tcp communication, and modified net js module to use the new driver via IO system.

Added TCP net module

---

esp32/main/targets/boards/esp32-devkitc/src/storage.c

EPS32 storage function implementation

---

esp32/main/esp32_main.c
esp32/main/targets/boards/esp32-devkitc/src/flash.c
esp32/main/targets/boards/esp32-devkitc/src/tty.c

ESP32 tty_read_sync function

---

esp32/main/targets/boards/esp32-devkitc/src/system.c

ESP32 system functions

---

esp32/main/targets/boards/esp32-devkitc/src/spi.c

spi_cleanup bug fix

---

esp32/main/targets/boards/esp32-devkitc/src/ieee80211.c

- Adding re-init the ieee80211_init()
- #283

Fix ieee80211_cleanup() function bug

---

cmake/CMakeLists.txt
cmake/kameleon-core.cmake
targets/boards/kameleon-core/target.cmake

- This is the base cmake build script for the other platforms including
Raspberry pi pico
- #223

CMake build env for the Kameleon core.

---

.gitmodules
CMakeLists.txt
targets/rpi-pico/board.js
targets/rpi-pico/include/linux.h
targets/rpi-pico/include/ringbuffer.h
targets/rpi-pico/src/adc.c
targets/rpi-pico/src/flash.c
targets/rpi-pico/src/gpio.c
targets/rpi-pico/src/i2c.c
targets/rpi-pico/src/pwm.c
targets/rpi-pico/src/ringbuffer.c
targets/rpi-pico/src/spi.c
targets/rpi-pico/src/storage.c
targets/rpi-pico/src/system.c
targets/rpi-pico/src/tty.c
targets/rpi-pico/src/uart.c
targets/rpi-pico/target.cmake
tools/kalamu.cmake

- Adding rp-pico target
- #295

Raspberrypi-pico build environment

---

targets/kameleon-core/target.cmake
targets/linux/target.cmake
targets/rpi-pico/target.cmake
tools/kaluma.cmake

Enable LTO option to optimize the code size
- #299

Fix typo in the cmake in the jerry script

---

targets/rpi-pico/src/system.c
targets/rpi-pico/src/tty.c
tools/kaluma.cmake

tty functions for REPL.

---

include/port/system.h
src/global.c
src/repl.c
targets/kameleon-core/include/kameleon_core.h
targets/kameleon-core/src/stm32f4xx_it.c
targets/kameleon-core/src/system.c
targets/linux/include/linux.h
targets/linux/src/system.c
targets/rpi-pico/board.js
targets/rpi-pico/include/rpi_pico.h
targets/rpi-pico/src/adc.c
targets/rpi-pico/src/system.c

System.c porting for rpi-pico board

---

src/jerry_port.c

Change jerryscript version to 2.3.0

---

targets/linux/src/adc.c
targets/rpi-pico/include/rpi_pico.h
targets/rpi-pico/src/adc.c
targets/rpi-pico/src/gpio.c
targets/rpi-pico/src/tty.c
targets/rpi-pico/target.cmake

rpi-pico ADC functions

---

include/port/i2c.h
targets/rpi-pico/include/rpi_pico.h
targets/rpi-pico/src/i2c.c
targets/rpi-pico/target.cmake

rpi-pico I2C functions

---

src/modules/spi/module_spi.c
targets/rpi-pico/include/rpi_pico.h
targets/rpi-pico/src/spi.c
targets/rpi-pico/target.cmake

rpi-pico SPI functions

---

include/port/system.h
src/repl.c
targets/kameleon-core/src/system.c
targets/linux/src/system.c
targets/rpi-pico/src/system.c

Delete firmup command

---

.gitmodules
tools/js2c.js
tools/kaluma.cmake

Move jerryscript to the lib

---

targets/rpi-pico/include/rpi_pico.h
targets/rpi-pico/src/i2c.c
targets/rpi-pico/src/pwm.c
targets/rpi-pico/src/spi.c
targets/rpi-pico/src/tty.c
targets/rpi-pico/src/uart.c
targets/rpi-pico/target.cmake

change static variable name
- #305

rpi-pico UART driver porting

---

include/port/flash.h
targets/kameleon-core/src/flash.c
targets/linux/src/flash.c
targets/rpi-pico/src/flash.c
targets/rpi-pico/src/tty.c
targets/rpi-pico/target.cmake

- flash program is not working and verified.
- #331

Flash tty update for rpi-pico

---

targets/rpi-pico/src/tty.c

Change printf to putchar

---

targets/rpi-pico/src/flash.c
targets/rpi-pico/src/tty.c

- ymodem code download is verified.
- #331

Bug fix in the flash and tty

---

include/port/storage.h
src/modules/storage/module_storage.c
targets/kameleon-core/src/storage.c
targets/rpi-pico/src/storage.c

rpi-pico storage API

---

targets/rpi-pico/src/system.c

Enable to start script in the main function

---

targets/rpi-pico/target.cmake

Change jerry heap size to 192k

---

targets/rpi-pico/board.js
targets/rpi-pico/include/rpi_pico.h
targets/rpi-pico/src/pwm.c

16 channel PWM for rpi-pico board

---

src/modules/uart/module_uart.c

Default UART buffer size is 2048 byte

---

.gitignore
CMakeLists.txt
targets/kameleon-core/target.cmake
targets/linux/target.cmake
targets/rpi-pico/target.cmake
tools/kaluma.cmake
tools/kaluma_config.h.in

Adding dependency for the generated source code.
- #351
- #333

Update the cmake build commands

---

targets/rpi-pico/src/gpio.c

- #369
@niklauslee Please reivew it.

Fix the bug - Pull up and pull down setting bug

---

src/modules/i2c/module_i2c.c

- Need to use JERRYXX_GET_ARG function with JERRYXX_HAS_ARG.
- #363

Fix the system stuck issue with desktop-clock script.

---

src/modules/i2c/module_i2c.c
src/modules/spi/module_spi.c

- Fix the bug in the SPI module
- #374

Fix JERRYXX_GET_ARG function

---

src/modules/wifi/module_wifi.c

- The same binary code after this change.

Change this_val to JERRYXX_GET_THIS

---

src/io.c

Add level events in setWatch function

---

include/port/pwm.h
src/global.c
src/modules/pwm/module_pwm.c
src/modules/pwm/pwm_magic_strings.h
targets/kameleon-core/src/pwm.c
targets/linux/src/pwm.c
targets/rpi-pico/src/pwm.c

PWM setInversion/getInversion function is implemented.
deadtime is not implemented. 
- #416

PWM inversion

---

src/global.c
src/jerryxx.c
src/modules/flash/module_flash.c
src/modules/graphics/module_graphics.c
src/modules/i2c/module_i2c.c
src/modules/pwm/module_pwm.c
src/modules/rp2/module_rp2.c
src/modules/sdcard/module_sdcard.c
src/modules/spi/module_spi.c
src/modules/stream/module_stream.c
src/modules/uart/module_uart.c
src/modules/vfs_lfs/module_vfs_lfs.c
targets/linux/src/main.c

Review memory allocation code and fix memory leakage.

---

src/modules/rp2/module_rp2.c
src/modules/rp2/rp2.js
targets/rp2/src/adc.c
targets/rp2/src/i2c.c

Pico-w internal temperature ADC

---

src/repl.c

Don't keep adding module commands to the help menu after soft reset

---

.vscode/launch.json
src/modules/pico_cyw43/module_pico_cyw43.c

Temporary disable DNS because dns function hake system hang issue

---

src/modules/pico_cyw43/module_pico_cyw43.c

Fix wifi connect callback issue

---

src/modules/graphics/gc_3bit_prims.c
src/modules/graphics/gc_3bit_prims.h
src/modules/graphics/module.cmake
src/modules/graphics/module_graphics.c

3bit color support (RBG111) for ILI9488

3bit color support for ILI9488

---

include/port/wdt.h
src/modules/wdt/module.cmake
src/modules/wdt/module.json
src/modules/wdt/module_wdt.c
src/modules/wdt/module_wdt.h
src/modules/wdt/wdt_magic_strings.h
targets/linux/src/wdt.c
targets/rp2/src/wdt.c
targets/rp2/target.cmake
targets/stm32/src/wdt.c

Implement watchdog class

---

src/global.c

- #622
- board.uid return uid string.

uid is moved to board object

---

targets/rp2/src/gpio.c

RP2040 GPIO input/ouput bug fix

---

targets/rp2/src/gpio.c

Reverts kaluma-project/kaluma#632

Revert "RP2040 GPIO input/ouput bug fix"

---

src/modules/rp2/module_rp2.c
src/modules/rp2/rp2.js
src/modules/rp2/rp2_magic_strings.h
targets/rp2/target.cmake

- Return BigInt type random number
- #649

Implement rp2 randomBigInt function

---

targets/rp2/boards/pico2-w/board.js

Pico2-w board file system mount point bug fix
